apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort  # Or ClusterIP + port-forward
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Access via http://<node-ip>:30080
  selector:
    app: nginx